/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courses;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Sahil Seewal
 */
public class admin_login extends javax.swing.JFrame {

    /**
     * Creates new form admin_login
     */
    public admin_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MV Boli", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("COURSE NAME");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 24)); // NOI18N
        jLabel2.setText("DETAILS OF COURSE");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "8th pass", "10th pass", "12th pass" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("neew");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);

        jLabel4.setFont(new java.awt.Font("MV Boli", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("SNO");

        jLabel5.setFont(new java.awt.Font("MV Boli", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 102, 0));
        jLabel5.setText("ENTER URL");

        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 0));
        jButton3.setText("HOME");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox2, 0, 158, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, 158, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addComponent(jButton1)
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                        .addGap(6, 6, 6))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(47, 47, 47)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          try
{
  
    //int j;
   /* 
String sql="Select* from course2";
ResultSet rs=stmt.executeQuery(sql);
//ResultSet pq=stmt.executeQuery(sql);
//j=0; */
    String s2=jTextField1.getText();
    String s1=jTextField2.getText();
    String s3=jTextArea1.getText();
     String s4=jTextField3.getText();
    Class.forName("java.sql.Driver");
String database="jdbc:mysql://localhost:3306/course8";
Connection conn=((Connection)DriverManager.getConnection(database,"root","root"));
Statement stmt=(Statement)conn.createStatement();
int pos=jComboBox1.getSelectedIndex();
int gos=jComboBox2.getSelectedIndex();

//int q=JOptionPane.showConfirmDialog(null,"Do you want to add course","CONFIRMATION BOX",JOptionPane.YES_NO_OPTION);
//if(q==0)
{
    if(pos==1 && gos==0)
{    String sql="insert into course1 values('"+s1+"','"+s2+"','"+s3+"','"+s4+"')";
stmt.executeUpdate(sql);

}
    
//int pos=jComboBox1.getSelectedIndex();    
if(pos==1 && gos==1)
{    //String s=rs.getString(1);
//String s1= rs.getString(2);
 String sql="insert into course1a1 values('"+s1+"','"+s2+"','"+s3+"','"+s4+"')";
stmt.executeUpdate(sql);

}
if(pos==1 && gos==2)
{
 String sql="insert into course1b values('"+s1+"','"+s2+"','"+s3+"','"+s4+"')";
stmt.executeUpdate(sql);
    
}
if(pos==2 && gos==0)
{
 String sql="insert into course2a values('"+s1+"','"+s2+"','"+s3+"','"+s4+"')";
stmt.executeUpdate(sql);
    
}
if(pos==2 && gos==1)
{
 String sql="insert into course2b values('"+s1+"','"+s2+"','"+s3+"','"+s4+"')";
stmt.executeUpdate(sql);
    
}
if(pos==2 && gos==2)
{
 String sql="insert into course2c values('"+s1+"','"+s2+"','"+s3+"','"+s4+"')";
stmt.executeUpdate(sql);
    
}

if(pos==2 && gos==3)
{
 String sql="insert into course2d values('"+s1+"','"+s2+"','"+s3+"','"+s4+"')";
stmt.executeUpdate(sql);
    
}
if(pos==3 && gos==0)
{
 String sql="insert into course3a values('"+s1+"','"+s2+"','"+s3+"','"+s4+"')";
stmt.executeUpdate(sql);
    
}
if(pos==3 && gos==4)
{
 String sql="insert into course3e values('"+s1+"','"+s2+"','"+s3+"','"+s4+"')";
stmt.executeUpdate(sql);
    
}
if(pos==3 && gos==1)
{
 String sql="insert into course3b values('"+s1+"','"+s2+"','"+s3+"','"+s4+"')";
stmt.executeUpdate(sql);
    
}
if(pos==3 && gos==2)
{
 String sql="insert into course3f values('"+s1+"','"+s2+"','"+s3+"','"+s4+"')";
stmt.executeUpdate(sql);
    
}
if(pos==3 && gos==3)
{
 String sql="insert into courseg values('"+s1+"','"+s2+"','"+s3+"','"+s4+"')";
stmt.executeUpdate(sql);
    
}


jTextField1.setText(" ");
  jTextField2.setText(" ");
  jTextArea1.setText(" ");
jTextField3.setText(" ");
  jTextField1.disable();
  jTextField2.disable();
  jComboBox1.disable();
  jComboBox2.disable();
  jButton1.hide();
  jTextArea1.disable();
  jTextField3.disable();
}
}
catch(Exception e)
{

System.out.print(" "+e);

}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
//  jButton1.enable();
 //jTextField1.enable();
// jTextField2.enable();
int pos=jComboBox1.getSelectedIndex();
int gos=jComboBox2.getSelectedIndex(); 
 try
{
    jTextField1.setText(" ");
 jTextField2.setText(" ");
 
    Class.forName("java.sql.Driver");
String database="jdbc:mysql://localhost:3306/course8";
Connection conn=((Connection)DriverManager.getConnection(database,"root","root"));
Statement stmt=(Statement)conn.createStatement();
//

//int flag=0;
//String s1;


/*s1=rs.getString(1);
i++;*/


int k=0;
if(pos==1 && gos==0)
{    //String sql="insert into course1 values('"+s1+"','"+s2+"' )";
String sql="Select* from course1a";
ResultSet rs=stmt.executeQuery(sql);
//stmt.executeUpdate(sql);

while(rs.next())
{
String s=rs.getString(1);
//String s= rs.getString(2);
k=Integer.parseInt(s);

}
k++;
jTextField2.enable();
jTextField2.setText(""+k);
}
    
//int pos=jComboBox1.getSelectedIndex();    
if(pos==1 && gos==1)
{    //String s=rs.getString(1);
//String s1= rs.getString(2);

    String t="Select* from course1a1";
ResultSet r=stmt.executeQuery(t);
//stmt.executeUpdate(sql);

while(r.next())
{
String s=r.getString(1);
//String s1= r.getString(2);
k=Integer.parseInt(s);
//is++;
}
k=k+1;
jTextField2.enable();
jTextField2.setText(""+ k);
 

}
if(pos==1 && gos==2)
{
 String sql="Select* from course1b";
ResultSet rs=stmt.executeQuery(sql);
//stmt.executeUpdate(sql);

while(rs.next())
{
String s=rs.getString(1);
//String s1= rs.getString(2);
k=Integer.parseInt(s);

}
k=k+1;
jTextField2.enable();
jTextField2.setText(""+k);

    
}
if(pos==2 && gos==0)
{
 String sql="Select* from course2a";
ResultSet rs=stmt.executeQuery(sql);
//stmt.executeUpdate(sql);

while(rs.next())
{
String s=rs.getString(1);
//String s1= rs.getString(2);
k=Integer.parseInt(s);

}
k=k+1;
jTextField2.enable();
jTextField2.setText(""+k);
   
}
if(pos==2 && gos==1)
{
 String sql="Select* from course2b";
ResultSet rs=stmt.executeQuery(sql);
//stmt.executeUpdate(sql);

while(rs.next())
{
String s=rs.getString(1);
//String s1= rs.getString(2);
k=Integer.parseInt(s);

}
k=k+1;
jTextField2.enable();
jTextField2.setText(""+k);
   
}

if(pos==2 && gos==2)
{
 String sql="Select* from course2c";
ResultSet rs=stmt.executeQuery(sql);
//stmt.executeUpdate(sql);

while(rs.next())
{
String s=rs.getString(1);
//String s1= rs.getString(2);
k=Integer.parseInt(s);

}
k=k+1;
jTextField2.enable();
jTextField2.setText(""+k);
   
}


if(pos==2 && gos==3)
{    //String sql="insert into course1 values('"+s1+"','"+s2+"' )";
String sql="Select* from course2d";
ResultSet rs=stmt.executeQuery(sql);
//stmt.executeUpdate(sql);

while(rs.next())
{
String s=rs.getString(1);
//String s= rs.getString(2);
k=Integer.parseInt(s);

}
k++;
jTextField2.enable();
jTextField2.setText(""+k);
}

if(pos==3 && gos==0)
{
 String sql="Select* from course3a";
ResultSet rs=stmt.executeQuery(sql);
//stmt.executeUpdate(sql);

while(rs.next())
{
String s=rs.getString(1);
//String s1= rs.getString(2);
k=Integer.parseInt(s);

}
k=k+1;
jTextField2.enable();
jTextField2.setText(""+k);

    
}

if(pos==3 && gos==4)
{
 String sql="Select* from course3e";
ResultSet rs=stmt.executeQuery(sql);
//stmt.executeUpdate(sql);

while(rs.next())
{
String s=rs.getString(1);
//String s1= rs.getString(2);
k=Integer.parseInt(s);

}
k=k+1;
jTextField2.enable();
jTextField2.setText(""+k);

    
}

if(pos==3 && gos==1)
{    //String sql="insert into course1 values('"+s1+"','"+s2+"' )";
String sql="Select* from course3b";
ResultSet rs=stmt.executeQuery(sql);
//stmt.executeUpdate(sql);

while(rs.next())
{
String s=rs.getString(1);
//String s= rs.getString(2);
k=Integer.parseInt(s);

}
k++;
jTextField2.enable();
jTextField2.setText(""+k);
}

if(pos==3 && gos==2)
{    //String sql="insert into course1 values('"+s1+"','"+s2+"' )";
String sql="Select* from course3f";
ResultSet rs=stmt.executeQuery(sql);
//stmt.executeUpdate(sql);

while(rs.next())
{
String s=rs.getString(1);
//String s= rs.getString(2);
k=Integer.parseInt(s);

}
k++;
jTextField2.enable();
jTextField2.setText(""+k);
}





if(pos==3 && gos==3)
{
 String sql="Select* from courseg";
ResultSet rs=stmt.executeQuery(sql);
//stmt.executeUpdate(sql);

while(rs.next())
{
String s=rs.getString(1);
//String s1= rs.getString(2);
k=Integer.parseInt(s);

}
k=k+1;
jTextField2.enable();
jTextField2.setText(""+k);
   
}
if(pos==3 && gos==4)
{
 String sql="Select* from courseg";
ResultSet rs=stmt.executeQuery(sql);
//stmt.executeUpdate(sql);

while(rs.next())
{
String s=rs.getString(1);
//String s1= rs.getString(2);
k=Integer.parseInt(s);

}
k=k+1;
jTextField2.enable();
jTextField2.setText(""+k);

    
}


if(pos==3 && gos==1)
{    //String sql="insert into course1 values('"+s1+"','"+s2+"' )";
String sql="Select* from course3b";
ResultSet rs=stmt.executeQuery(sql);
//stmt.executeUpdate(sql);

while(rs.next())
{
String s=rs.getString(1);
//String s= rs.getString(2);
k=Integer.parseInt(s);

}
k++;
jTextField2.enable();
jTextField2.setText(""+k);
}


jTextField1.setText(" ");
//  jTextField2.setText(" ");
  jTextArea1.setText(" ");
  jTextField3.setText(" ");



}

catch(Exception e)
{

System.out.print(" "+e);

}

 
 
       
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:

 jButton1.setVisible(false);
 jTextField1.disable();
 jTextField2.disable();
 jComboBox1.disable();
 jComboBox2.disable();
 jTextArea1.disable();
 jTextField3.disable();
setTitle("  ADD  COURSES"); 
    }//GEN-LAST:event_formWindowGainedFocus

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        try
{
    
    //int j;
   /* Class.forName("java.sql.Driver");
String database="jdbc:mysql://localhost:3306/course8";
Connection conn=((Connection)DriverManager.getConnection(database,"root","root"));
Statement stmt=(Statement)conn.createStatement();
String sql="Select* from course2";
ResultSet rs=stmt.executeQuery(sql);
//ResultSet pq=stmt.executeQuery(sql);
//j=0; */
int pos=jComboBox1.getSelectedIndex();
//int gos=jComboBox2.getSelectedIndex();

if(pos==0)
{
    jComboBox2.removeAllItems();
jComboBox2.addItem(" ");
}
if(pos==1)
{    //String s=rs.getString(1);
//String s1= rs.getString(2);
jComboBox2.removeAllItems();
jComboBox2.addItem("SERVICE COURSES");
jComboBox2.addItem("INDUSTRIAL COURSES");
jComboBox2.addItem("AGRICULTURAL COURSES");

}
    
//int pos=jComboBox1.getSelectedIndex();    
if(pos==2)
{    //String s=rs.getString(1);
//String s1= rs.getString(2);
jComboBox2.removeAllItems();
jComboBox2.addItem("SERVICE COURSES");
jComboBox2.addItem("INDUSTRIAL COURSES");
jComboBox2.addItem("AGRICULTURAL COURSES");
jComboBox2.addItem("DIPLOMA COURSES");
}
if(pos==3)
{
    jComboBox2.removeAllItems();
jComboBox2.addItem("MEDICAL");
jComboBox2.addItem("NON MEDICAL");
jComboBox2.addItem("COMMERCE");
jComboBox2.addItem("ARTS");
jComboBox2.addItem("COURSES COMMON TO STREAM");
//jComboBox2.addItem("sss");
}
}
catch(Exception e)
{

System.out.print(" "+e);

}

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
  //      jComboBox1.enable();
 //jComboBox2.enable();
// jButton1.show();
jButton1.setVisible(true); 
jTextField1.enable();
 //jTextField2.enable();
 jComboBox1.enable();
 jComboBox2.enable();
 jTextArea1.enable();
 jTextField3.enable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                front_page p=new front_page();
        this.hide();
        p.show();

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
